account/urls.py
from django.conf.urls import patterns, url

from account import views

urlpatterns = patterns('',
                       url(r'^$', views.account_list, name='account_list'),
                       url(r'^new$', views.account_create, name='account_new'),
                       url(r'^edit/(?P<pk>\d+)$', views.account_update, name='account_edit'),
                       url(r'^delete/(?P<pk>\d+)$', views.account_delete, name='account_delete'),
)

client/urls.py
from django.conf.urls import patterns, url

from client import views

urlpatterns = patterns('',
                       url(r'^$', views.client_list, name='client_list'),
                       url(r'^new$', views.client_create, name='client_new'),
                       url(r'^edit/(?P<pk>\d+)$', views.client_update, name='client_edit'),
                       url(r'^profile/(?P<pk>\d+)$', views.client_profile, name='client_profile'),
                       url(r'^delete/(?P<pk>\d+)$', views.client_delete, name='client_delete'),
)

laboratorio4/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^client/', include('client.urls', namespace='client')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^cashier/', include('cashier.urls', namespace='cashier')),
    url(r'^transaction/', include('transaction.urls', namespace='transaction')),
]

client/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Client(models.Model):
    firstName = models.CharField(max_length=100, blank=True)
    lastName = models.CharField(max_length=100, blank=True)
    dni = models.CharField(max_length=9, blank=True)
    address = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=10, blank=True)
    email = models.CharField(max_length=30, blank=True)

    def __unicode__(self):
        return self.firstName + " " + self.lastName

    def get_absolute_url(self):
        return reverse('client:client_edit', kwargs={'pk': self.pk})

client/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from client.models import Client
from account.models import Account

class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = ['firstName', 'lastName', 'dni', 'address', 'phone', 'email']

def client_list(request, template_name='client/client_list.html'):
    client = Client.objects.all()
    data = {'object_list': client}
    return render(request, template_name, data)

def client_create(request, template_name='client/client_form.html'):
    form = ClientForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('client:client_list')
    return render(request, template_name, {'form': form})

def client_update(request, pk, template_name='client/client_form.html'):
    client = get_object_or_404(Client, pk=pk)
    form = ClientForm(request.POST or None, instance=client)
    if form.is_valid():
        form.save()
        return redirect('client:client_list')
    return render(request, template_name, {'form': form})

def client_delete(request, pk, template_name='client/client_confirm_delete.html'):
    client = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        client.delete()
        return redirect('client:client_list')
    return render(request, template_name, {'objects': client})

def client_profile(request, pk, template_name='client/client_profile.html'):
    client = get_object_or_404(Client, pk=pk)
    accounts = Account.objects.filter(client=pk).values()
    data = {'client': client, 'accounts': accounts}
    return render(request, template_name, data)

client/templates/client/client_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

client/templates/client/client_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

client/templates/client/client_list.html
<h1>Client</h1>
<ul>
    {% for client in object_list %}
    <li>{{ client.firstName }}  ({{ client.lastName }})
    <a href="{% url 'client:client_edit' client.id %}">edit</a>
    <a href="{% url 'client:client_profile' client.id %}">Profile</a>
    <a href="{% url 'client:client_delete' client.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'client:client_new' %}">New</a>

client/templates/client/client_profile.html
<h1>Cliente</h1>
<ul>
    <h2>{{ client.firstName }}  {{ client.lastName }} </h2>
    <li> DNI: {{ client.dni }}</li>
    <li> Dirección: {{ client.address }}</li>
    <li> Teléfono: {{ client.phone }}</li>
    <li> Correo: {{ client.email }}</li>
    <a href="{% url 'client:client_edit' client.id %}">Editar</a>
    </br>
    </br>
    <li> Cuentas: </li>
    <table border="1" style="width:60%">
        <tr align="center">
            <td>Id</td>
            <td>Saldo</td>
            <td>Estado</td>
            <td colspan="2">Acciones</td>
        </tr>
        {% for account in accounts %}
        <tr>
            <td>{{ account.id }}</td>
            <td>{{ account.amount }}</td>
            {% if account.status == True %}
                <td>Activo</td>
            {% else %}
                <td>Inactivo</td>
            {% endif %}
            <td><a href="{% url 'account:account_edit' account.id %}">Revisar</a></td>
            <td><a href="{% url 'account:account_edit' account.id %}">Movimiento</a></td>
        </tr>
        {% endfor %}

    </table>
</ul>